version: "3.8"

services:
  backend:
    build: ./backend
    container_name: math-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/persistent_db:/app/persistent_db
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  frontend:
    build: ./my-app
    container_name: math-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
